DESI-LS: Add functions to create catalog and download images
AstroPile/AstroPile_prototype pull request #23
Opened 2024-03-26 21:28 UTC by mwalmsley

Add two new scripts for DECaLS (aka DESI-LS as we include sister surveys):
- Query LS-DR10 TAP database to grab RA/Dec and key columns. Save as .parquet
- Given RA/Dec etc., construct a query url for the cutout server to grab the fits image.

Easy arguments for pixel size, depth and bands. TBD among community.

Note: astropile currently has DESI-LS images via Stein's HDF5 export. This is an alternative to recreate those images with e.g. different native pixel sizes, as requested by @EiffL

2024-04-11 14:40 UTC, mhuertascompany requested changes

2024-04-11 14:40 UTC, mhuertascompany commented on scripts/decals/build_galaxy10_sample.py
change the filename to "build_parent_sample.py" for consistency with other datasets

2024-04-11 14:40 UTC, mhuertascompany commented on scripts/decals/build_galaxy10_sample.py
> +        f.create_dataset('image_array', (len(df), 3, 224, 224))  # no values yet
the image size is hard coded - perhaps try to make it clear somewhere in the code with a global variable and replace all numerical values by the global variable name

2024-04-11 14:40 UTC, mhuertascompany commented on scripts/decals/decals.py
why is the image size here 152?

2024-04-11 14:40 UTC, mhuertascompany commented on scripts/decals/create_images_from_cutout_server.py
> +        pixel_size=424,
another image size - please homogenize

2024-04-11 14:40 UTC, mhuertascompany commented on scripts/decals/build_galaxy10_sample.py
> +    base_dir = Path('/Users/user/repos/zoobot-foundation/foundation/datasets/custom_downstream/decals10')
check this local paths. are they needed?

2024-04-11 14:40 UTC, mhuertascompany commented on scripts/decals/build_galaxy10_sample.py
> +    train_df = pd.read_parquet(base_dir / 'decals10_train.parquet')
is is downloading the data?

2024-04-11 14:40 UTC, mhuertascompany commented on baselines/dataset_utils.py
since the priority for now is to have the datasets ready, I'd recommend to 2 different PRs. One for the data and the other for the baselines. I have not reviewed the baseline part.

2024-04-25 20:31 UTC, EiffL commented
Thanks both, I'll have a go at implementing @mhuertascompany 's comments

2024-04-26 18:26 UTC, EiffL commented
Ok, I did a lot of digging, I think I know how to generate the cutouts directly from the tiles saved at NERSC, that will be much much faster than going through the cutout API, and will even avoid having to transfer all the native data over. 

I'm setting up the scripts, and we will use our polymathic hours at NERSC to execute the job. I'll open a new PR for that part of the problem. Once that works, we can remove from this PR the data download part and concentrate on the baseline code.

2024-04-30 19:25 UTC, mwalmsley commented
Hello. I will go ahead and remove the cutout download part. Please send comments on the baseline part.

2024-05-08 16:47 UTC, mwalmsley commented
Closing for a fresh baseline PR, using GZ10 
See #47

2024-05-08 16:47 UTC, closed without merging