Add JWST data
AstroPile/AstroPile_prototype pull request #42
Opened 2024-04-03 19:13 UTC by mhuertascompany

Adding scripts to create JWST imaging datasets

2024-04-04 14:56 UTC, EiffL requested changes
This looks very good! could you just remove some of the experimental code that you had and commented text just to make it cleaner.

2024-04-04 14:56 UTC, EiffL commented on scripts/jwst/.DS_Store
Please remove

2024-04-04 14:56 UTC, EiffL commented on scripts/jwst/build_parent_sample.py
> +                        'image_psf_fwhm': image,
Can you compute the FWHM somehow? For space based it's fine to have a single number

2024-04-04 14:56 UTC, EiffL commented on scripts/jwst/build_parent_sample.py
> +                        'image_psf_fwhm': image,
And you can add another entry for 'image_psf_array'

2024-04-04 14:56 UTC, EiffL commented on scripts/jwst/build_parent_sample.py
> +            #s_x = min([stamp.shape[0] for f in filter_list])
can you remove the commented text?

2024-04-04 14:56 UTC, EiffL commented on scripts/jwst/build_parent_sample.py
> +            #ra = row['ra']  # Assuming there is a 'ra' column
where is my ra and dec?

2024-04-04 14:56 UTC, EiffL commented on scripts/jwst/build_parent_sample.py
> +            #ra = row['ra']  # Assuming there is a 'ra' column
Ok good, maybe remove the commented code :-)

2024-04-04 14:56 UTC, EiffL commented on scripts/jwst/jwst.py
> +                'psf_fwhm': Array2D(shape=(self._image_size, self._image_size), dtype='float32'),
This should be updated to return a scalar number

2024-04-04 14:56 UTC, EiffL commented on scripts/jwst/jwst.py
> +                    #print(data['image_band'][i][j].decode('utf-8'))
remove commented code

2024-04-04 14:56 UTC, EiffL commented on scripts/jwst/jwst_old.py
to be removed

2024-04-23 16:09 UTC, LTMeyer commented
Tests are now passing. The issue was related to how tables were obtained and multiple downloads and dataset processing in the same folder. The `cosmos` field was also problematic. @mhuertascompany solved these problems.

I removed the commented or unused code, formatted it with ruff and sorted the imports.
I don't know if @EiffL 's remaining comments have been addressed (for returning a scalar number and adding another entry for `image_psf_array`).

2024-04-25 20:34 UTC, EiffL approved these changes
I made some small modifications, and I think it's all good to merge.

2024-04-25 20:34 UTC, merged